---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/name: hummingbird-jiangok
  name: hummingbird-jiangok
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/jiangok2006/hummingbird_jiangok-ops.git
        revision: HEAD
        directories:
          - path: overlay/*/*/*
          #       overlay/{environment}/{cluster}/{app}
          #       0       /1            /2        /3        
          #       overlay/staging/in-cluster/hummingbird-jiangok
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      labels:
        environment: "{{index .path.segments 1}}"
        service: "{{index .path.segments 3}}"
      name: "{{index .path.segments 3}}"
    spec:
      destination:
        name: "{{index .path.segments 2}}"
        namespace: "{{.path.basename}}"
      project: hummingbird-jiangok
      source:
        path: "{{.path.path}}"
        repoURL: https://github.com/jiangok2006/hummingbird_jiangok-ops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
