---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
  name: hummingbird-jiangok-staging
  namespace: hummingbird-jiangok-staging
spec:
  # Deny all cluster-scoped resources from being created, except for Namespace
  # This is needed by our ApplicationSets, which specify `syncOptions` with `CreateNamespace=true`
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  description: Project for the hummingbird_jiangok service staging
  destinations:
    - namespace: hummingbird-jiangok-staging
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/jiangok2006/hummingbird_jiangok-ops.git
